source ~/.profile

# alias for clang toolchain
# Make sure to run mkdir     "${HOME}/.npm-packages"

# useful for code style
# CPPLINT is powered by Google
# pip3 install --user cpplint
# pip3 install --user cppman

# fucking shit
stty -ixon

# to update npm
NPM_PACKAGES="${HOME}/.npm-packages"

PATH="$NPM_PACKAGES/bin:$PATH"

# SAmple command
 # clang-check -analyze hell.cpp --
# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

alias analyzeCC='clang++ --analyze -std=c++14 -stdlib=libc++ -Xanalyzer -analyzer-output=text'
alias analyzeC='clang --analyze -std=c11 -Xanalyzer -analyzer-output=text'

alias asshole='unSetting ; defaultSetting'
alias mysql='mysql -u root -p'

alias clang-format='clang-format-3.6'

alias cxx="clang++ -ggdb3 -O0 -std=c++14 -stdlib=libc++ -lc++abi -Werror -Wself-assign -Wall -pedantic-errors -Wextra-tokens -Wambiguous-member-template -Wbind-to-temporary-copy -fdiagnostics-print-source-range-info -fdiagnostics-show-template-tree -ferror-limit=33 -ftemplate-backtrace-limit=13 -lpthread -l:libmagic.so.1"

alias ccc="clang -ggdb3 -O0 -std=c11 -Wall -Werror -pedantic-errors"

# gcc or g++ compiler
alias gcc="gcc -O0 -g -std=c11 -Wall -Wextra -Wshadow -pedantic -Werror"
# for effective C++ optimization
alias gxx="g++ -O0 -g -std=c++14 -Wall -Wextra -Wshadow -pedantic -Weffc++ -fdiagnostics-color=always -l sqlite3"
alias gxx="g++ -O0 -g -std=c++14 -Wall -Wextra -Wshadow -pedantic -Weffc++ -fdiagnostics-color=always"

# Custom aliases folder dir
alias author="cd ~/Dropbox/FUNProgramming/ehz_notebook"
alias github="cd ~/Dropbox/FUNProgramming/"
# alias apublic="cd ~/vhosts/localhost/public/"
alias metacpp="cd ~/Dropbox/metadata/cppDeitel/Code_Examples"
alias free="free -h"

alias sag="sudo apt-get"
alias update50="pullall"

# my nootbook
alias ehz="vim ~/Dropbox/FUNProgramming/ehz_notebook/ehzNOTEBOOK.txt"

# My aliases
alias sqlite="sqlite3"
alias v="vim"
alias t="tmux"
alias vinp="vim --noplugin"
alias vinn="vim -u NONE"
alias c="clear"

# Updating process
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
# alias dist-upgrade='sudo apt-get dist-upgrade'

# all at once
alias pullall='update ; upgrade'
alias housekeeping='sudo apt-get autoclean && sudo apt-get autoremove'

# git command aliases
alias Gadd="git add"
alias Gdiff="git diff"
alias Gshow="git show"
alias Gcommit="git commit"
alias Gstatus="git status"
alias Glog="git log"
alias Gpush="git push origin master"
alias Gpull="git pull origin master"

# custom configuration

# If not running interactively, don't do anything else
[ -z "$PS1" ] && return

PS1='\[\e[0;37m\]\u@\[\e[0;37m\]\h\[\e[0;35m\](\w):\[\e[0m\]$(__git_ps1 "(%s)") '

# If this is an xterm set the title to user@host(dir):
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# # configure prompt tail working directory
# if [ "$PS1" ]; then
#   export PS1="\[\e[0;46m\]\u@\[\e[0;46m\]\h\[\e[0;34m\](\W):\[\e[0m\] "
# fi

# # configure prompt present working directory
# if [ "$PS1" ]; then
#   export PS1="\[\e[0;46m\]\u@\[\e[0;46m\]\h\[\e[0;34m\](\w):\[\e[0m\] "
# fi


 # set umask
umask 0077

# configure man
export MANSECT="3,2,1"

# Warning...Can cause trouble when compile system software

# protect user
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# convenience
alias ll="ls -l --color=auto"
alias gdb="gdb -q"

# allow core dumps
ulimit -c unlimited

# set editor
export EDITOR=vim

# linking personalized ~/.bash_profile with ~/.bashrc
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

# git bash completion
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
export CLASSPATH=.:/usr/lib/spl.jar

